// <auto-generated />
namespace GrupoLTM.WebSmart.Domain.Repository.Configuration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TabelasExtratoNormalizadas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TabelasExtratoNormalizadas));
        
        string IMigrationMetadata.Id
        {
            get { return "201609061943012_TabelasExtratoNormalizadas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
