// <auto-generated />
namespace GrupoLTM.WebSmart.Domain.Repository.Configuration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CampoLoteTabelasImportacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CampoLoteTabelasImportacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201608222043239_CampoLoteTabelasImportacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
